config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only: [:index, :new, :create, :destroy]   
   root "resumes#index"  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :name, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController   
  def index   
     @resumes = Resume.all   
  end   
     
  def new   
     @resume = Resume.new   
  end   
     
  def create   
     @resume = Resume.new(resume_params)   
        
     if @resume.save   
        redirect_to resumes_path, notice: "Successfully uploaded."   
     else   
        render "new"   
     end   
        
  end   
     
  def destroy   
     @resume = Resume.find(params[:id])   
     @resume.destroy   
     redirect_to resumes_path, notice:  "Successfully deleted."   
  end   
     
  private   
     def resume_params   
     params.require(:resume).permit(:name, :attachment)   
  end   
     
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>   
 <head>   
      <title>File Uploading</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>   
      
   <body>   
      <div>   
         <%= yield %>   
      </div>   
   </body>   
</html>  

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<%= link_to "<button>New Entry</button>".html_safe, new_resume_path %>   
<br>   
<br>   
  
<table border="3">   
   <thead>   
      <tr>   
         <th>Candidate Name</th>   
         <th>Download Link</th>   
         <th>Action</th>   
      </tr>   
   </thead>   
      
   <tbody>   
      <% @resumes.each do |resume| %>   
            
         <tr>   
            <td><%= resume.name %></td>   
            <td><%= link_to "<button>Download</button>".html_safe, resume.attachment_url %></td>   
            <td><%= button_to "Delete",  resume, method: :delete, confirm: "Are you sure you want to delete #{resume.name}?" %></td>   
         </tr>   
            
      <% end %>   
   </tbody>   
      
</table>   
</div>  

app/views/resumes/new.html.erb
<div class="container">   
<% if !@resume.errors.empty? %>   
   <div>   
         
      <ul>   
         <% @resume.errors.full_messages.each do |msg| %>   
            <li><%= msg %></li>   
         <% end %>      </ul>   
         
   </div>   
<% end %>   
  
<div>   
   <%= form_for @resume, html: { multipart: true } do |f| %>   
      <%= f.label :name %>   
      <%= f.text_field :name %>   
      <br><br>   
      <%= f.label :attachment %>   
      <%= f.file_field :attachment %>
      <br>
      <%= f.submit "Submit" %>   
         
   <% end %>   
</div>   
</div>  